apiVersion: v1
kind: ConfigMap
metadata:
  name: cast-service-config
data:
  DATABASE_URI: "postgresql://{{ .Values.cast.database.user }}:{{ .Values.cast.database.password }}@cast-db:5432/{{ .Values.cast.database.name }}"  
