apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: "{{ .Values.cast.image.repository }}:{{ .Values.cast.image.tag }}"
          ports:
            - containerPort: {{ .Values.cast.service.port }}
          command: 
            - uvicorn            
          args:
            - app.main:app
            - --host
            - 0.0.0.0
            - --port
            - "8000"
            - --loop
            - asyncio                               
          env:
            - name: DATABASE_URI
              valueFrom:
                configMapKeyRef:
                  name: cast-service-config
                  key: DATABASE_URI
