apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-service-config
data:  
  DATABASE_URI: "postgresql://{{ .Values.movie.database.user }}:{{ .Values.movie.database.password }}@movie-db:5432/{{ .Values.movie.database.name }}"
